# Generated by Django 5.1 on 2024-11-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=250)),
                ('experience', models.FloatField(default=0)),
                ('completedprojects', models.IntegerField(default=0)),
                ('awards', models.IntegerField(default=0)),
                ('clients', models.IntegerField(default=0)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('myimage', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
