# Generated by Django 5.1 on 2024-11-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0002_alter_mydetails_awards_alter_mydetails_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetails',
            name='awards',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mydetails',
            name='clients',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mydetails',
            name='completedprojects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mydetails',
            name='experience',
            field=models.FloatField(default=0),
        ),
    ]
