# Generated by Django 5.1 on 2024-11-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0004_about_mystack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyStack',
        ),
        migrations.AddField(
            model_name='about',
            name='stacklogo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='about',
            name='stackname',
            field=models.CharField(default='', max_length=250),
        ),
    ]
