# Generated by Django 5.1 on 2024-11-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0006_remove_about_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='stackname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
