# Generated by Django 5.1 on 2024-11-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0008_alter_mydetails_myimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='stacklogo',
            new_name='stackimage',
        ),
    ]
