# Generated by Django 5.1 on 2024-11-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0009_rename_stacklogo_about_stackimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=80)),
                ('service', models.CharField(max_length=50)),
                ('servicedesc', models.CharField(max_length=250)),
            ],
        ),
    ]
