# Generated by Django 5.1 on 2024-11-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0010_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=80)),
                ('projectfilter', models.CharField(max_length=50)),
                ('projectdesc', models.CharField(max_length=250)),
                ('projectimg', models.ImageField(upload_to='projects/')),
            ],
        ),
    ]
