# Generated by Django 5.1 on 2024-11-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0011_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
