# Generated by Django 5.1 on 2024-11-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0013_testimonials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='stackimage',
            field=models.ImageField(null=True, upload_to='stack/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='stackname',
            field=models.CharField(max_length=50),
        ),
    ]
