# Generated by Django 5.1 on 2024-11-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0015_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
