# Generated by Django 5.1 on 2024-11-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0016_delete_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='clientplace',
            field=models.IntegerField(default=1),
        ),
    ]
