# Generated by Django 5.1 on 2024-11-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0017_testimonials_clientplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonials',
            name='clientplace',
        ),
        migrations.RemoveField(
            model_name='testimonials',
            name='creation_date',
        ),
        migrations.AlterField(
            model_name='testimonials',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
