# Generated by Django 5.1 on 2024-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioapp', '0018_remove_testimonials_clientplace_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profileimage', models.ImageField(null=True, upload_to='stack/')),
                ('span', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=80)),
                ('profilebio', models.CharField(max_length=250)),
            ],
        ),
    ]
